/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgottenPasswordRouteImport } from './routes/forgotten-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTagsRouteImport } from './routes/dashboard/tags'
import { Route as DashboardProjectsRouteImport } from './routes/dashboard/projects'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardFocusRouteImport } from './routes/dashboard/focus'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardSplatRouteImport } from './routes/dashboard/$'
import { Route as DashboardTasksIndexRouteImport } from './routes/dashboard/tasks/index'
import { Route as DashboardTasksTaskIdRouteImport } from './routes/dashboard/tasks/$taskId'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgottenPasswordRoute = ForgottenPasswordRouteImport.update({
  id: '/forgotten-password',
  path: '/forgotten-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTagsRoute = DashboardTagsRouteImport.update({
  id: '/tags',
  path: '/tags',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFocusRoute = DashboardFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSplatRoute = DashboardSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksIndexRoute = DashboardTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTasksTaskIdRoute = DashboardTasksTaskIdRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tasks': typeof DashboardTasksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/$': typeof DashboardSplatRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/projects': typeof DashboardProjectsRoute
  '/dashboard/tags': typeof DashboardTagsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/tasks/$taskId': typeof DashboardTasksTaskIdRoute
  '/dashboard/tasks/': typeof DashboardTasksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/$'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/tags'
    | '/dashboard/'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tasks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/$'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/tags'
    | '/dashboard'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tasks'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/$'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/projects'
    | '/dashboard/tags'
    | '/dashboard/'
    | '/dashboard/tasks/$taskId'
    | '/dashboard/tasks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgottenPasswordRoute: typeof ForgottenPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotten-password': {
      id: '/forgotten-password'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof ForgottenPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tags': {
      id: '/dashboard/tags'
      path: '/tags'
      fullPath: '/dashboard/tags'
      preLoaderRoute: typeof DashboardTagsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/projects': {
      id: '/dashboard/projects'
      path: '/projects'
      fullPath: '/dashboard/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/focus': {
      id: '/dashboard/focus'
      path: '/focus'
      fullPath: '/dashboard/focus'
      preLoaderRoute: typeof DashboardFocusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$': {
      id: '/dashboard/$'
      path: '/$'
      fullPath: '/dashboard/$'
      preLoaderRoute: typeof DashboardSplatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/': {
      id: '/dashboard/tasks/'
      path: '/tasks'
      fullPath: '/dashboard/tasks/'
      preLoaderRoute: typeof DashboardTasksIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/tasks/$taskId': {
      id: '/dashboard/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/dashboard/tasks/$taskId'
      preLoaderRoute: typeof DashboardTasksTaskIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardSplatRoute: typeof DashboardSplatRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardFocusRoute: typeof DashboardFocusRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardTagsRoute: typeof DashboardTagsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardTasksTaskIdRoute: typeof DashboardTasksTaskIdRoute
  DashboardTasksIndexRoute: typeof DashboardTasksIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSplatRoute: DashboardSplatRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardFocusRoute: DashboardFocusRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardTagsRoute: DashboardTagsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardTasksTaskIdRoute: DashboardTasksTaskIdRoute,
  DashboardTasksIndexRoute: DashboardTasksIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgottenPasswordRoute: ForgottenPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
