/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgottenPasswordRouteImport } from './routes/forgotten-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DashboardTasksRouteImport } from './routes/dashboard/tasks'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardOverviewRouteImport } from './routes/dashboard/overview'
import { Route as DashboardFocusRouteImport } from './routes/dashboard/focus'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'

const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgottenPasswordRoute = ForgottenPasswordRouteImport.update({
  id: '/forgotten-password',
  path: '/forgotten-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTasksRoute = DashboardTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOverviewRoute = DashboardOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFocusRoute = DashboardFocusRouteImport.update({
  id: '/focus',
  path: '/focus',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
}
export interface FileRoutesByTo {
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgotten-password': typeof ForgottenPasswordRoute
  '/login': typeof LoginRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/register': typeof RegisterRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/focus': typeof DashboardFocusRoute
  '/dashboard/overview': typeof DashboardOverviewRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/tasks': typeof DashboardTasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/dashboard'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/dashboard'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/tasks'
  id:
    | '__root__'
    | '/dashboard'
    | '/forgotten-password'
    | '/login'
    | '/privacy-policy'
    | '/register'
    | '/terms-of-service'
    | '/dashboard/calendar'
    | '/dashboard/focus'
    | '/dashboard/overview'
    | '/dashboard/profile'
    | '/dashboard/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgottenPasswordRoute: typeof ForgottenPasswordRoute
  LoginRoute: typeof LoginRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RegisterRoute: typeof RegisterRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgotten-password': {
      id: '/forgotten-password'
      path: '/forgotten-password'
      fullPath: '/forgotten-password'
      preLoaderRoute: typeof ForgottenPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tasks': {
      id: '/dashboard/tasks'
      path: '/tasks'
      fullPath: '/dashboard/tasks'
      preLoaderRoute: typeof DashboardTasksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/overview': {
      id: '/dashboard/overview'
      path: '/overview'
      fullPath: '/dashboard/overview'
      preLoaderRoute: typeof DashboardOverviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/focus': {
      id: '/dashboard/focus'
      path: '/focus'
      fullPath: '/dashboard/focus'
      preLoaderRoute: typeof DashboardFocusRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardFocusRoute: typeof DashboardFocusRoute
  DashboardOverviewRoute: typeof DashboardOverviewRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardTasksRoute: typeof DashboardTasksRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardFocusRoute: DashboardFocusRoute,
  DashboardOverviewRoute: DashboardOverviewRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardTasksRoute: DashboardTasksRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  DashboardRoute: DashboardRouteWithChildren,
  ForgottenPasswordRoute: ForgottenPasswordRoute,
  LoginRoute: LoginRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RegisterRoute: RegisterRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
